const ROMAN_NUMERALS = {
  I: 1,
  V: 5,
  X: 10,
  L: 50,
  C: 100,
  D: 500,
  M: 1000
};

const ROMAN_NUMERALS_VALIDATOR_REGEX =
  "^M{0,3}(CM|CD|D?C{0,3})(XC|XL|L?X{0,3})(IX|IV|V?I{0,3})$";

const TRANSLATION_STATEMENT_VALIDATOR_REGEX = /is [IVXLCDM]/gi;
const RESOURCE_PRICE_STATEMENT_VALIDATOR_REGEX = /([0-9]+)/g;
const QUERY_STATEMENT_VALIDATOR_REGEX = /\?/g;

module.exports = {
  ROMAN_NUMERALS,
  ROMAN_NUMERALS_VALIDATOR_REGEX,
  TRANSLATION_STATEMENT_VALIDATOR_REGEX,
  RESOURCE_PRICE_STATEMENT_VALIDATOR_REGEX,
  QUERY_STATEMENT_VALIDATOR_REGEX
};
